version: '3.8'
services:
  app:
    image: api_testkominfo
    container_name: api_testkominfo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:9000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: admin_api
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
